const { Router } = require("express");
const jobs = require("./jobs");
const feed = require("./feed");
const companies = require("./companies");
const router = Router();
const swaggerUi = require("swagger-ui-express");
const swaggerDocument = require("../../../docs/swagger.json");
router.use("/jobs", jobs);
router.use("/companies", companies);
router.use("/feed", feed);
router.use("/doc", swaggerUi.serve, swaggerUi.setup(swaggerDocument));
module.exports = router;
